//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VO.Parking.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.ParkingHistories = new HashSet<ParkingHistory>();
        }
    
        public int Id { get; set; }
        public string LicenseNumber { get; set; }
        public int ParkingUsedCount { get; set; }
        public System.DateTime FirtsTimeEntryDate { get; set; }
        public System.DateTime LastTimeEntryDate { get; set; }
        public int CarParkingStatus { get; set; }
    
        public virtual ParkingCar ParkingCar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkingHistory> ParkingHistories { get; set; }
    }
}
