//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VO.Parking.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkingDbContext : DbContext
    {
        public ParkingDbContext()
            : base("name=ParkingDbConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<ParkingCar> ParkingCars { get; set; }
        public virtual DbSet<ParkingHistory> ParkingHistories { get; set; }
        public virtual DbSet<ParkingState> ParkingStates { get; set; }
    }
}
